## 1.0 Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

%matplotlib inline

## 2.0 Load the dataset

In [2]:
df = pd.read_csv('data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

## 3.0 Rename columns and Normalize string values

In [3]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
string_columns = list(df.dtypes[df.dtypes == 'object'].index)
for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

## 4.0 Fix dtypes

In [4]:
total_charges = pd.to_numeric(df['totalcharges'], errors='coerce')

df['totalcharges'] = pd.to_numeric(df['totalcharges'], errors='coerce')
df['totalcharges'] = df['totalcharges'].fillna(0)

## 5.0 Normalize class column values

In [5]:
df['churn'] = (df['churn'] == 'yes').astype(int)

## 6.0 Train, validation and test split

In [6]:
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=43)

In [7]:
y_train = df_train['churn'].values
y_val = df_val['churn'].values

In [8]:
del df_train['churn']
del df_val['churn']

## 7.0 Exploratory Data Analisys

### 7.1 Check null values

In [11]:
df_train_full.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

### 7.2 Check class distribution

In [12]:
df_train_full['churn'].value_counts()

0    4138
1    1496
Name: churn, dtype: int64

* Class Imbalance (CI)

In [ ]:
CI = (na - nd)/(na + nd)

In [18]:
(df_train_full[df_train_full['churn']==1]['churn'].count()-df_train_full[df_train_full['churn']==0]['churn'].count())/(df_train_full[df_train_full['churn']==1]['churn'].count()+df_train_full[df_train_full['churn']==0]['churn'].count())

-0.46893858714944975

### 7.3 Check the number of unique values for each categorical feature

In [13]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents', 'phoneservice', 'multiplelines',
               'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection','techsupport',
               'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod']

numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [16]:
df_train_full[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

### 7.4 Feature importance

#### 7.4.1 Proportion Difference and Risk Ratio

In [20]:
from IPython.display import display

global_mean = df_train_full['churn'].mean()
for col in categorical:
    df_group = df_train_full.groupby(by=col)['churn'].agg(['mean'])
    df_group['diff'] = df_group['mean'] - global_mean
    df_group['rate'] = df_group['mean'] / global_mean
    display(df_group)

            mean      diff      rate
gender
female  0.270841  0.005310  1.019998
male    0.260478 -0.005053  0.980971

                   mean      diff      rate
seniorcitizen
0              0.237098 -0.028433  0.892922
1              0.413907  0.148377  1.558793

             mean      diff      rate
partner
no       0.326446  0.060916  1.229411
yes      0.200733 -0.064798  0.755968

                mean      diff      rate
dependents
no          0.312326  0.046795  1.176233
yes         0.155674 -0.109856  0.586276

                  mean      diff      rate
phoneservice
no            0.253623 -0.011908  0.955156
yes           0.266824  0.001293  1.004871

                      mean      diff      rate
multiplelines
no                0.251397 -0.014134  0.946771
no_phone_service  0.253623 -0.011908  0.955156
yes               0.284105  0.018574  1.069952

                     mean      diff      rate
internetservice
dsl              0.191851 -0.073679  0.722521
fiber_optic      0.415558  0.150028  1.565010
no               0.076606 -0.188924  0.288502

                         mean      diff      rate
onlinesecurity
no                   0.416014  0.150484  1.566727
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.145342 -0.120189  0.547363

                         mean      diff      rate
onlinebackup
no                   0.398693  0.133162  1.501494
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.216531 -0.048999  0.815467

                         mean      diff      rate
deviceprotection
no                   0.387706  0.122175  1.460117
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.226825 -0.038705  0.854234

                         mean      diff      rate
techsupport
no                   0.413472  0.147941  1.557153
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.152855 -0.112676  0.575657

                         mean      diff      rate
streamingtv
no                   0.335418  0.069887  1.263197
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.298945  0.033415  1.125841

                         mean      diff      rate
streamingmovies
no                   0.333333  0.067803  1.255348
no_internet_service  0.076606 -0.188924  0.288502
yes                  0.301320  0.035789  1.134784

                    mean      diff      rate
contract
month-to-month  0.426533  0.161002  1.606340
one_year        0.117987 -0.147544  0.444343
two_year        0.028379 -0.237151  0.106878

                     mean      diff      rate
paperlessbilling
no                0.16414 -0.101390  0.618159
yes               0.33594  0.070409  1.265164

                               mean      diff      rate
paymentmethod
bank_transfer_(automatic)  0.174475 -0.091056  0.657080
credit_card_(automatic)    0.152404 -0.113126  0.573961
electronic_check           0.449921  0.184390  1.694420
mailed_check               0.190328 -0.075203  0.716782

#### 7.4.2 Mutual Information

In [22]:
from sklearn.metrics import mutual_info_score

df_mi = df_train_full[categorical].apply(lambda x: mutual_info_score(x, df_train_full['churn']))
df_mi = df_mi.sort_values(ascending=False).to_frame(name='MI')
df_mi

                        MI
contract          0.096652
onlinesecurity    0.063393
techsupport       0.060935
internetservice   0.053313
onlinebackup      0.045424
paymentmethod     0.042861
deviceprotection  0.042007
streamingtv       0.030844
streamingmovies   0.030705
paperlessbilling  0.019077
dependents        0.014129
partner           0.010227
seniorcitizen     0.010059
multiplelines     0.000654
gender            0.000069
phoneservice      0.000040

#### 7.4.3 Correlation Coeficient

In [23]:
df_train_full[numerical].corrwith(df_train_full['churn'])

tenure           -0.344925
monthlycharges    0.188574
totalcharges     -0.193370
dtype: float64

### 7.5 Feature Engineering